export { createPresentationManager } from './manager.js';
export type {
  CancelReason,
  DismissReason,
  InputOf,
  LaneConfig,
  LaneSnapshot,
  ManagerOptions,
  PresentationContract,
  PresentationEvent,
  PresentationHandle,
  PresentationLifecycleEvent,
  PresentationManager,
  PresentationOptions,
  PresentationOutcome,
  PresentationPhase,
  PresentationRequestSnapshot,
  PresentationSnapshot,
  PresentationStrategy,
  ResultOf,
} from './types.js';
